import type { Metadata } from "next";
import "./styles/index.css";
import "./styles/globals.css";
import { Mona_Sans } from "next/font/google";

const plusJakarta = Mona_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakarta.variable} font-sans bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
