import type { Metadata } from "next";
import "./styles/index.css";
import localFont from "next/font/local";

const polysansBulky = localFont({
  src: "../public/fonts/polysans-bulky.woff2",
  variable: "--font-polysans-bulky",
  display: "swap",
});

const polysansSlim = localFont({
  src: "../public/fonts/polysans-slim.woff2",
  variable: "--font-polysans-slim",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${polysansBulky.variable} ${polysansSlim.variable} font-body bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
